// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location.proto

package location

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Points are represented as latitude-longitude pairs in the E7 representation
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
type Point struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{0}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type DistanceRequest struct {
	Point1               *Point   `protobuf:"bytes,1,opt,name=point1,proto3" json:"point1,omitempty"`
	Point2               *Point   `protobuf:"bytes,2,opt,name=point2,proto3" json:"point2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistanceRequest) Reset()         { *m = DistanceRequest{} }
func (m *DistanceRequest) String() string { return proto.CompactTextString(m) }
func (*DistanceRequest) ProtoMessage()    {}
func (*DistanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{1}
}

func (m *DistanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistanceRequest.Unmarshal(m, b)
}
func (m *DistanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistanceRequest.Marshal(b, m, deterministic)
}
func (m *DistanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistanceRequest.Merge(m, src)
}
func (m *DistanceRequest) XXX_Size() int {
	return xxx_messageInfo_DistanceRequest.Size(m)
}
func (m *DistanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DistanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DistanceRequest proto.InternalMessageInfo

func (m *DistanceRequest) GetPoint1() *Point {
	if m != nil {
		return m.Point1
	}
	return nil
}

func (m *DistanceRequest) GetPoint2() *Point {
	if m != nil {
		return m.Point2
	}
	return nil
}

type DistanceResponse struct {
	Distance             float64  `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistanceResponse) Reset()         { *m = DistanceResponse{} }
func (m *DistanceResponse) String() string { return proto.CompactTextString(m) }
func (*DistanceResponse) ProtoMessage()    {}
func (*DistanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f0f35158dcf9f2c, []int{2}
}

func (m *DistanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistanceResponse.Unmarshal(m, b)
}
func (m *DistanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistanceResponse.Marshal(b, m, deterministic)
}
func (m *DistanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistanceResponse.Merge(m, src)
}
func (m *DistanceResponse) XXX_Size() int {
	return xxx_messageInfo_DistanceResponse.Size(m)
}
func (m *DistanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DistanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DistanceResponse proto.InternalMessageInfo

func (m *DistanceResponse) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "location.Point")
	proto.RegisterType((*DistanceRequest)(nil), "location.DistanceRequest")
	proto.RegisterType((*DistanceResponse)(nil), "location.DistanceResponse")
}

func init() { proto.RegisterFile("location.proto", fileDescriptor_4f0f35158dcf9f2c) }

var fileDescriptor_4f0f35158dcf9f2c = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xc9, 0x4f, 0x4e,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x1c,
	0xb9, 0x58, 0x03, 0xf2, 0x33, 0xf3, 0x4a, 0x84, 0xa4, 0xb8, 0x38, 0x72, 0x12, 0x4b, 0x32, 0x4b,
	0x4a, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x18, 0x83, 0xe0, 0x7c, 0x21, 0x19, 0x2e, 0xce,
	0x9c, 0xfc, 0xbc, 0x74, 0x88, 0x24, 0x13, 0x58, 0x12, 0x21, 0xa0, 0x94, 0xcc, 0xc5, 0xef, 0x92,
	0x59, 0x5c, 0x92, 0x98, 0x97, 0x9c, 0x1a, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xa4, 0xce,
	0xc5, 0x56, 0x00, 0x32, 0xd5, 0x10, 0x6c, 0x14, 0xb7, 0x11, 0xbf, 0x1e, 0xdc, 0x01, 0x60, 0xdb,
	0x82, 0xa0, 0xd2, 0x70, 0x85, 0x46, 0x60, 0x63, 0x71, 0x2a, 0x34, 0x52, 0xd2, 0xe3, 0x12, 0x40,
	0x58, 0x52, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x0a, 0x72, 0x72, 0x0a, 0x54, 0x0c, 0xe6, 0x64, 0x18,
	0xdf, 0xc8, 0x9f, 0x8b, 0xc3, 0x07, 0x6a, 0x92, 0x90, 0x33, 0x17, 0x07, 0x4c, 0xaf, 0x90, 0x24,
	0xc2, 0x02, 0x34, 0x47, 0x4b, 0x49, 0x61, 0x93, 0x82, 0x58, 0xa5, 0xc4, 0x90, 0xc4, 0x06, 0x0e,
	0x39, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x55, 0xa1, 0x61, 0x4b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LocationClient is the client API for Location service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LocationClient interface {
	Distance(ctx context.Context, in *DistanceRequest, opts ...grpc.CallOption) (*DistanceResponse, error)
}

type locationClient struct {
	cc *grpc.ClientConn
}

func NewLocationClient(cc *grpc.ClientConn) LocationClient {
	return &locationClient{cc}
}

func (c *locationClient) Distance(ctx context.Context, in *DistanceRequest, opts ...grpc.CallOption) (*DistanceResponse, error) {
	out := new(DistanceResponse)
	err := c.cc.Invoke(ctx, "/location.Location/Distance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocationServer is the server API for Location service.
type LocationServer interface {
	Distance(context.Context, *DistanceRequest) (*DistanceResponse, error)
}

// UnimplementedLocationServer can be embedded to have forward compatible implementations.
type UnimplementedLocationServer struct {
}

func (*UnimplementedLocationServer) Distance(ctx context.Context, req *DistanceRequest) (*DistanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Distance not implemented")
}

func RegisterLocationServer(s *grpc.Server, srv LocationServer) {
	s.RegisterService(&_Location_serviceDesc, srv)
}

func _Location_Distance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocationServer).Distance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/location.Location/Distance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocationServer).Distance(ctx, req.(*DistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Location_serviceDesc = grpc.ServiceDesc{
	ServiceName: "location.Location",
	HandlerType: (*LocationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Distance",
			Handler:    _Location_Distance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "location.proto",
}
